# Generated by Django 4.2.7 on 2023-12-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserData',
        ),
    ]
