# Generated by Django 4.2.7 on 2023-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsApp', '0002_rename_employee_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='estado',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('inactivo', 'INACTIVO')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fono',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
